In [5]:
import numpy as np
import torch
import tensorflow as tf

In [7]:
# Creating a numpy array
x = np.array([2,3,5])
# crating a torch tensor  vector
xpt = torch.tensor([2,3,5.]) 
# craring a tenseflow variable
xtf = tf.Variable([2,3,5.])

In [8]:
x

array([2, 3, 5])

In [9]:
xpt

tensor([2., 3., 5.])

In [11]:
xtf

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([2., 3., 5.], dtype=float32)>

In [12]:
y = x + 1
y

array([3, 4, 6])

In [13]:
np.dot(x,y)

48

In [14]:
# crating a pytorch tensor variable
ypt = torch.tensor([9,6,5.])
ypt

tensor([9., 6., 5.])

In [15]:
torch.dot(xpt,ypt)

tensor(61.)

In [17]:
# creating a tensor variable with tensorflow
ytf = tf.Variable([9,6,5.])
ytf

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([9., 6., 5.], dtype=float32)>

In [19]:
# usinfg teditional metjod for dot product in tensorflow multipication then add
tf.reduce_sum(tf.multiply(xtf,ytf))

<tf.Tensor: shape=(), dtype=float32, numpy=61.0>

In [22]:
# dot producrt using tenflow varibale
tf.tensordot(xtf, ytf, 1)

<tf.Tensor: shape=(), dtype=float32, numpy=61.0>