In [1]:
print("Hello Numpy")

Hello Numpy


In [2]:
import numpy as np

Basic Operation on the Numpy

In [3]:
a = np.arange(6) # a range of array from 0 tp specifide number
print(a)
print(a[0])
print(type(a[0]))

[0 1 2 3 4 5]
0
<class 'numpy.int64'>


In [4]:
a = np.array([1,2,3,4,5,6])
print(a)
print(a[0])
print(type(a[0]))
ap = a[np.newaxis, ]
print(ap)
print(ap.shape)

[1 2 3 4 5 6]
1
<class 'numpy.int64'>
[[1 2 3 4 5 6]]
(1, 6)


In [5]:
a = np.ones(6) # crate an 1-D array of 6 elements with by default float64
a = np.ones(6,dtype=np.int64)
print(a)
print(a[0])
type(a[0])

[1 1 1 1 1 1]
1


numpy.int64

In [6]:
a = np.empty(6) #crate an 1-D array of 6 elements with by default float64
print(a)
print(a[0])
print(type(a[0]))

[1. 1. 1. 1. 1. 1.]
1.0
<class 'numpy.float64'>


In [12]:
# linespace : here you can a make parts specific like num=4 into 4 parts
arr = np.linspace(0, 10, num = 5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


Sorting Of an array

In [8]:
# sorting of an array
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


Adding arrays or joining arrays 

In [9]:
# COncatanating two array adding into the array
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.concatenate((a,b))
print(c)

[1 2 3 4 5 6 7 8]


In [17]:
# Concatanating on the basis of an axis
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

c = np.concatenate((x,y), axis=0)
print(c)
ct = np.concatenate((x.T, ), axis=1)
print(ct)
cn = np.concatenate((x, y), axis=None)
print(cn)
print(c.shape,ct.shape,cn.shape)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[1 2 3 4 5 6]
(3, 2) (2, 3) (6,)
