# Checking Shape and size

In [2]:
import numpy as np

In [2]:
arr = np.array([[[0,1,2,3,4],[4,5,6,7,8]],

                 [[0,1,2,3,4],[4,5,6,7,8]],

                 [[0,1,2,3,4],[4,5,6,7,8]]])

In [5]:
arr.ndim

3

In [6]:
arr.size

30

In [7]:
arr.shape

(3, 2, 5)

# Reshaping of an array 

In [8]:
a = np.arange(6)
print(a)
b = a.reshape(3,2)
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


# Indexing and Sclicing 

In [5]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(a[0][2],a[1][2],a[2][2])

3 7 11


In [7]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(a[a < 10])

[1 2 3 4 5 6 7 8 9]


In [8]:
print(a < 10)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True False False False]]


In [9]:
print(a[a % 2 == 0])

[ 2  4  6  8 10 12]


In [10]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [12]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a < 10)
print(b)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0]))


In [13]:
list_of_coordinates= list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)


(0, 0)
(0, 1)
(0, 2)
(0, 3)
(1, 0)
(1, 1)
(1, 2)
(1, 3)
(2, 0)


In [14]:
print(a[b])

[1 2 3 4 5 6 7 8 9]


In [15]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))
